package com.server.backend.entity;

import jakarta.persistence.*;
import java.sql.Date;
import lombok.*;

/**
 * Entity representing an availability period for a person.
 * <p>
 * This entity is used to store the periods during which a person is available
 * to work.
 * Each availability period is linked to a specific person by their ID.
 * The class is annotated with Lombok's {@code @Data} to automatically generate
 * getters, setters, {@code toString}, {@code equals}, and {@code hashCode}
 * methods.
 */

@Entity
@Table(name = "availability")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Availability {
    /**
     * Unique identifier for the availability period, this is auto generated by the
     * database management system and is the primary key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer availabilityId;

    /**
     * ID mapping to the person this availability period is associated with. This
     * is a foreign key mapping to the person entity
     */
    @Column(name = "person_id")
    private Integer personId;

    /**
     * The start date of the availability period.
     */
    @Column(name = "from_date")
    private Date fromDate;

    /**
     * The end date of the availability period.
     */
    @Column(name = "to_date")
    private Date toDate;
}
