package com.server.backend.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity representing a specific competence or skill.
 * <p>
 * The {@link Data} annotation from Lombok is used to automatically generate
 * getters, setters, and other common methods like {@code toString},
 * {@code equals}, and {@code hashCode}.
 */
@Entity
@Table(name = "competence")
@Data
@NoArgsConstructor
@AllArgsConstructor

public class Competence {
    /**
     * The unique identifier for a competence. This ID is automatically generated by
     * the database when a new competence is created.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer competenceId;

    /**
     * The name of the competence. This field stores the descriptive name of the
     * skill or competence.
     */
    private String name;
}
