package com.server.backend.entity;

import java.math.BigDecimal;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity representing a competence profile belonging to a person.
 * <p>
 * The {@link Data} annotation from Lombok is used to automatically generate
 * getters, setters, and other common methods like {@code toString},
 * {@code equals}, and {@code hashCode}.
 */
@Entity
@Table(name = "competence_profile")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CompetenceProfile {
    /**
     * The unique identifier for a competence profile. This ID is automatically
     * generated by
     * the database when a new competence profile is created.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer competenceProfileId;

    /**
     * ID mapping to the person this competence profile is associated with. This
     * is a foreign key mapping to the person entity
     */
    @Column(name = "person_id")
    private Integer personId;

    /**
     * ID mapping to the competence this competence profile is associated with. This
     * is a foreign key mapping to the competence entity
     */
    @Column(name = "competence_id")
    private Integer competenceId;

    /**
     * How many years of experience the person has for the given competence
     */
    @Column(name = "years_of_experience")
    private BigDecimal yearsOfExperience;
}
