package com.server.backend.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity representing a person.
 * <p>
 * Contains user credentials password and username.
 * <p>
 * The {@link Data} annotation from Lombok is used to automatically generate
 * getters, setters, and other common methods like {@code toString},
 * {@code equals}, and {@code hashCode}.
 */
@Entity
@Table(name = "person")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Person {

    /**
     * The unique identifier for a person. This ID is automatically
     * generated by
     * the database when a new Person is created.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer personId;
    /**
     * The name of the person
     */
    private String name;
    /**
     * The persons surname
     */
    private String surname;
    /**
     * Personal number of a person
     */
    private String pnr;
    /**
     * Email belonging to a person
     */
    private String email;
    /**
     * A persons chosen password for account
     */
    private String password;

    /**
     * ID mapping to the role of this person.
     * This is a foreign key mapping to the Role entity.
     */
    @Column(name = "role_id")
    private Integer roleId;

    /**
     * A persons chosen username for account
     */
    private String username;
}
