package com.server.backend.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity representing a role.
 * <p>
 * Role is used for authorization.
 * <p>
 * The {@link Data} annotation from Lombok is used to automatically generate
 * getters, setters, and other common methods like {@code toString},
 * {@code equals}, and {@code hashCode}.
 */
@Entity
@Table(name = "role")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Role {
    /**
     * The unique identifier for a Role. This ID is automatically
     * generated by
     * the database when a new Role is created.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer roleId;

    /**
     * The name of the role
     */
    private String name;
}
